name: mango
description: A new type of ridesharing app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

module:
  androidX: true

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.11
  # camera: ^0.5.5 
  sliding_up_panel: ^1.0.2
  flutter_google_places: any
  geocoder: ^0.2.1
  flutter_polyline_points: ^0.1.0
  geolocator: ^5.1.3
  provider: ^4.1.3
  cloud_functions: ^0.5.0
  geoflutterfire: any


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.0+9
  #  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2
    #
    #  # Add the dependencies for any other Firebase products you want to use in your app
  #  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth: ^0.14.0+5
  google_sign_in: ^4.0.4
  cloud_firestore: ^0.13.7
  badges: ^1.1.1
  settings_ui: ^0.3.0
  flutter_config: 1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.0"

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/runr.png
    - assets/runr_no_circle.png
    - assets/mango.png
    - assets/missingmango.png
    - assets/baggins.png
    - assets/elf.png
    - assets/marley.png
    - assets/google_logo.png
    - assets/bagginso.png
    - assets/elfo.png
    - assets/marlo.png
    - assets/destination_map_marker.png
    - assets/driving_pin.png
    - assets/prediction_pin.png
    - assets/pullup_rectangle.png
    - assets/fonts/Quicksand-Bold.ttf
    - assets/terms.txt
    - assets/licenses.txt
    # These fonts are unused, but are here in case we need them
    # - assets/fonts/Quicksand-Light.ttf
    # - assets/fonts/Quicksand-Regular.ttf
    # - assets/fonts/Quicksand-Medium.ttf
    # - assets/fonts/Quicksand-SemiBold.ttf


        # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf